# Site settings
title: Richards Page
email: kubikriso@gmail.com
facebook: "https://www.facebook.com/richard.kubik11?ref=bookmarks"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
